/*
 * msg_proc.c: implementation of the remote procedure
 * "printmessage"
 */
 
#include <stdio.h>
#include <rpc/rpc.h>  /* always needed */
#include "msg.h"      /* msg.h will be generated by rpcgen */
 
/*
 * Remote version of "printmessage"
 */
int *
printmessage_1_svc(msg, rqstp)
        char **msg;
	struct svc_req *rqstp;
{
        static int result; /* must be static! */
        FILE *f;
 
        f = fopen("/dev/console", "w");
        if (f == NULL) {
                result = 0;
                return (&result);
        }
        fprintf(f, "%s\n", *msg);
        fclose(f);
        result = 1;
        return (&result);
}

