/*
 * rls.c: Remote directory listing client
 */
#include <stdio.h>
#include <rpc/rpc.h>    /* always need this */
#include <errno.h>
#include "dir.h"        /* will be generated by rpcgen */
 
//extern int errno;
 
main(int argc, char *argv[])
{
        CLIENT *cl;
        char *server;
        char *dir;
        readdir_res *result;
        namelist nl;
 
        if (argc != 3) {
                fprintf(stderr, "usage: %s host directory\n",
                  argv[0]);
                exit(1);
        }
 
        server = argv[1];
        dir = argv[2];
 
        /*
         * Create client "handle" used for calling DIRPROG on
         * the server designated on the command line.  Use
         * the tcp protocol when contacting the server.
         */
        cl = clnt_create(server, DIRPROG, DIRVERS, "tcp");
        if (cl == NULL) {
                /*
                 * Couldn't establish connection with server.
                 * Print error message and stop.
                 */
                clnt_pcreateerror(server);
                exit(1);
        }
 
        /*
         * Call the remote procedure readdir on the server
         */
        result = readdir_1(&dir, cl);
        if (result == NULL) {
                /*
                 * An RPC error occurred while calling the server.
                 * Print error message and stop.
                 */
                clnt_perror(cl, server);
                exit(1);
        }
 
        /*
         * Okay, we successfully called the remote procedure.
         */
        if (result->error != 0) {
                /*
                 * A remote system error occurred.
                 * Print error message and stop.
                 */
                errno = result->error;
                perror(dir);
                exit(1);
        }
 
        /*
         * Successfully got a directory listing.
         * Print it out.
         */
        for (nl = result->readdir_res_u.list; nl != NULL;
          nl = nl->next) {
                printf("%s\n", nl->name);
        }

	xdr_free((xdrproc_t)xdr_readdir_res, (char *)result);
        exit(0);
}


