#!/bin/csh
# Request one file at a time for the specified number of requests
# using a new connection for each request

# Some basic configuration
set show_replies = 1
set server      = "127.0.0.1"

if ($#argv != 1) then
  echo "Usage : $0 num_requests"
  exit 1
endif

set conns       = "--num-conns $1"
# Empty here becase we do one request at a time
# See also runrate
set rate        = ""

# Request 10 byte file (assume userver is started in src dir)
set uri         = "--uri docs/100K.txt"
set httperf     = "httperf"
set httpversion = "--http-version 1.1"
set timeout     = "--timeout 3"
set port        = "--port 6800"
set extraopts   = "--verbose --hog"

if ($show_replies) then
  set print = "--print-reply"
else
  set print = ""
endif

$httperf $extraopts --server $server $port $httpversion $uri \
         $conns $timeout $print $rate

exit $status
