#!/bin/csh
# Request one file at a time for the specified number of requests
# using the same connection for all requests

# Some basic configuration
set show_replies = 1
set server      = "127.0.0.1"

if ($#argv != 1) then
  echo "Usage : $0 num_requests"
  exit 1
endif

set numcalls    = "--num-calls $1"
set conns       = "--num-conns 1"
set rate        = ""

# Request 10 byte file (assume userver is started in src dir)
set uri         = "--uri docs/10B.txt"
set httperf     = "httperf"
set httpversion = "--http-version 1.1"
set timeout     = "--timeout 10"
set port        = "--port 6800"
set extraopts   = "--verbose --hog"

if ($show_replies) then
  set print = "--print-reply"
else
  set print = ""
endif

$httperf $extraopts --server $server $port $httpversion $uri \
         $conns $timeout $print $rate $numcalls

exit $status
