#!/bin/csh
# Request files at the specified rate for specified number of times

# Some basic configuration
set show_replies = 0
set server      = "127.0.0.1"

if ($#argv != 2) then
  echo "Usage : $0 rate num_requests"
  exit 1
endif

set rate        = "--rate $1"
set conns       = "--num-conns $2"

# Request 10 byte file (assume userver is started in src dir)
set uri         = "--uri docs/10B.txt"
set httperf     = "httperf"
set httpversion = "--http-version 1.1"
set timeout     = "--timeout 10"
set port        = "--port 6800"
set extraopts   = "--verbose --hog "

if ($show_replies) then
  set print = "--print-reply"
else
  set print = ""
endif

$httperf $extraopts --server $server $port $httpversion $uri \
         $conns $timeout $print $rate

exit $status
