#!/bin/csh
set server  =  localhost
# set print   = --print-reply
set print   = 
set timeout = 3
set uri     = docs/1K.txt
set port    = 80
set conns   = 30000
set rate   = "--rate 3000"
# set rate   =
httperf --verbose --hog --server $server --port $port --http-version 1.1 --uri $uri --num-conns $conns $rate --timeout $timeout $print
