#!/bin/csh
set server  =  $1
set print   = --print-reply
# set print   = 
set timeout = 3
set uri     = esc_stats_print
set port    = 6800
httperf --verbose --server $server --port $port --http-version 1.1 --uri $uri --timeout $timeout $print
